version: '2.3'

services:
  api:
    build: ./server
    # for prod, use node over nodemom
    command: nodemon ./src/server.js
    # for prod, no volume mounting source code
    volumes:
      - ./server/src:/home/node/src
    ports:
      - "4000:4000"
    environment:
      - MONGO_HOST=db
      - SENDGRID_API_KEY
      - SPA_BASE_URL
      - API_BASE_URL
      - MONGO_DB
      - MONGO_USER
      - MONGO_PASS

  db:
    build: ./mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_DB
      - MONGO_USER
      - MONGO_PASS
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb

  frontend:
    build:
      context: ./static
      target: dev
    volumes:
      - frontend-dist:/home/node/dist
      - ./static/src:/home/node/src
      - ./static/loaders:/home/node/loaders
      - ./static/public:/home/node/public
      - ./static/webpack.config.js:/home/node/webpack.config.js
      - ./static/webpack.node.js:/home/node/webpack.node.js
    command: webpack --watch

  caddy:
    image: abiosoft/caddy
    volumes:
      - ./Caddyfile.dev:/etc/Caddyfile
      - frontend-dist:/srv
    ports:
      - 4001:80

volumes:
  mongo-data:
    driver: local
  mongo-configdb:
    driver: local
  frontend-dist:
    driver: local
