version: '2'

services:
  frontend:
    image: us.gcr.io/biohacks-194200/biohacks:ab8e9935850a3a11b7bebfcb8913f1c6afc970bc
    volumes:
      - frontend-static:/app

  caddy:
    image: abiosoft/caddy
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - .caddy:/root/.caddy
      - frontend-static:/srv
    ports:
      - 80:80
      - 443:443

volumes:
  frontend-static:
    driver: local
