version: '2'

services:
  api:
    build: ./server
    # for prod, use node over nodemom
    command: ./node_modules/.bin/nodemon server.js
    # for prod, no volume mounting source code
    volumes:
      - ./server:/home/node
    ports:
      - "4000:4000"
    environment:
      - MONGO_HOST=db
      - SENDGRID_API_KEY
      - SPA_BASE_URL
      - API_BASE_URL
      - MONGO_DB
      - MONGO_USER
      - MONGO_PASS

  db:
    build: ./mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_DB
      - MONGO_USER
      - MONGO_PASS
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb

volumes:
  mongo-data:
    driver: local
  mongo-configdb:
    driver: local
