version: '2'

services:
  frontend:
    image: us.gcr.io/biohacks-194200/biohacks:5dcb2ec7532a6c52b500b16815604d58f871b457
    volumes:
      - frontend-static:/app

  caddy:
    image: abiosoft/caddy
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - .caddy:/root/.caddy
      - frontend-static:/srv
    ports:
      - 80:80
      - 443:443

volumes:
  frontend-static:
    driver: local
